language: python

python:
    - "2.7"

sudo: false  # Use container-based infrastructure
cache:
  directories:
    - $HOME/.cache/pip  # cache pip requirements
services:
  - mongodb

env:
  - CONSUL_V=0.5.0

before_install:
  # Install SCSS
  - gem install sass
install:
  - pip install -r config/requirements.txt
  - pip install flake8
  # Install Consul
  - wget "https://dl.bintray.com/mitchellh/consul/${CONSUL_V}_linux_amd64.zip"
  - unzip "${CONSUL_V}_linux_amd64.zip"
  - ./consul --version

before_script:
  - flake8 app/
  - flake8 script/
  - flake8 config
  - flake8 test/
  - mkdir log
script:
  # Run tests
  - ./run_tests.sh

