language: python

python:
    - "2.7"

sudo: false  # Use container-based infrastructure
cache: pip   # Cache pip requirements

env:
  global:
    - PORT=5000
    - HOST=0.0.0.0
    - DEBUG=TRUE
    - SECRET_KEY=abc123

git:  # We need custom git configurations
    submodules: false
before_install:  # Use sed to replace the SSH URL with the public URL
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - pip install -r config/requirements.txt
  - pip install flake8
before_script:
  - flake8 app/
  - flake8 script/
  - flake8 test/
script:
  - nosetests
