language: python

python:
    - "2.7"

env:
  global:
    # general settings
    - PORT=5000
    - HOST=0.0.0.0
    - DEBUG=TRUE
    - SECRET_KEY=abc123

git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - pip install -r config/requirements.txt
  - pip install flake8

before_script: "flake8 pyramid_genshi --ignore=E501,W291,W293"
# command to run tests


script:
  - flake8 app/
  - nosetests
