sudo: false

language: python
python:
  - "2.7"

cache: pip
services:
  - mongodb

before_install:
  # Install SCSS
  - gem install sass
  - source config/secrets.travis
install:
  - pip install -r config/requirements.txt

before_script:
  - mkdir log
script:
  - flake8
  - pytest --verbose app/
