language: python

python:
    - "2.7"

# sudo: false  # Use container-based infrastructure
# cache:
#   directories:
#     - $HOME/.cache/pip  # cache pip requirements
services:
  - mongodb

env:
  global:
    # Use environment variables
    - USE_ENV_VARS=TRUE
    # Flask settings
    - PORT=5000
    - HOST=0.0.0.0
    - DEBUG=TRUE
    - SECRET_KEY=abc123
    # Google OAuth settings
    - INSTALLED_APP_CLIENT_SECRET_PATH=client_secrets.json
    - CREDENTIALS_PATH=config/credentials.json
    - GOOGLE_AUTH_ENABLED=TRUE
    - CLIENT_SECRETS_PATH=config/client_secrets.json
    # Cross-site request forgery settings
    - CSRF_ENABLED=TRUE
    - CSRF_SESSION_KEY=def456
    # Google Calendar settings
    - PRIVATE_CALENDAR_ID='a@group.calendar.google.com'
    - PUBLIC_CALENDAR_ID='b@group.calendar.google.com'
    # MongoDB settings
    - MONGO_DATABASE=eventum
    # Logging settings
    - LOG_FILE_MAX_SIZE=256   # in MB
    - APP_LOG_NAME=log/app.log
    - WERKZEUG_LOG_NAME=log/werkzeug.log

git:  # We need custom git configurations
    submodules: false
before_install:  # Use sed to replace the SSH URL with the public URL
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - pip install -r config/requirements.txt
  - pip install flake8
script:
  - flake8 app/
  - flake8 script/
  - flake8 test/

